---
output:
  pdf_document: default
  html_document: default
---

# Problem Statement
ShippingtoMali, a shipping company, provides shipping to Mali for items bought on Amazon at a
rate of 4 dollars for the first item and $2 for each subsequent item with each of those items is also
subject to import 10% tax. During this time, they also have a $10 discount for orders worth
above $500.
Write an R program that prints out how much one would spend for both purchase and shipping
of the given items ('item 1', 'item 2', 'item 3', 'item 4', 'item 5', 'item 6', 'item 7') from the given
data that is stored in the vectors or lists.
We can write two functions that will help provide a solution to this problem.

● One function will iterate over the price list/vector (120, 32, 99, 49, 99, 75, 30) applying
the respective tax and appending the result to the total_cost list/vector.

● The other function will take the number of items in an order as its only parameter then
return the cost of shipping the function's result. This function would only display the
shipping charge


```{r}
# Let's create a function with parameters
# ---
#

#Returns the prices of the items after applying the 10% tax
after_tax_prices <- function(){
  total_prices <- c(length = 7)
  prices <- c(120, 32, 99, 49, 99, 75, 30)
  i = 1
  while(i <= length(prices)) {
    total_prices[[i]] <- prices[i]*1.1
    i <- i + 1
  }
  return(total_prices)
}
print("Prices after taxation")
after_tax_prices()

cost_of_shipping <- function(number_of_items){
  shipping_cost <- 0
  if (number_of_items == 1) {
    shipping_cost <- 4
  } else {
    shipping_cost <- 4 + ((number_of_items-1)*2)
  }
  
  return(shipping_cost)
}
print("cost of shipping")
cost_of_shipping(3)

total_cost_of_shipping <-function(number_of_items) {
  total_cost_of_shipping <- cost_of_shipping(number_of_items) + sum(after_tax_prices()[1:number_of_items])
  
  #This checks if the customer qualifies for the discount
  if(total_cost_of_shipping >= 500) {
    total_cost_of_shipping <- total_cost_of_shipping - 10
  }
  return(total_cost_of_shipping)
}

print("cost of shipping plus prices (total cost)")
total_cost_of_shipping(3)
```
